### ISSUE TITLE
Question: logEvent creates demand

### ISSUE THREAD

**Issue by n0c1urne** [sirthias/swave#17]
Currently, you can inspect the message flow using `logEvent("SomeMarker")`. However, attaching this inspection actually creates demand itself, changing the semantics of the flow - which effectively means a program with logging has a different backpressure flow than without logging - opening up for "heisenbugs". I don't know the consequences of changing this, however it should probably be mentioned in the documentation.

**Comment by sirthias** [comment]
`logEvent` does not introduce demand by itself. It simply sits in the pipe and inspects what's going through. Maybe the example you were looking at actually *did* have demand coming in from downstream?

**Comment by n0c1urne** [comment]
Oh yeah, sorry, my example was messed up. Thanks for clarifying.
