### ISSUE TITLE
Scala 2.10

### ISSUE THREAD

**Issue by fommil** [sirthias/swave#18]
I noticed that you only release for 2.11, but we cross build ensime for 2.10... Is there a technical reason not to build for 2.10?

**Comment by sirthias** [comment]
With 2.12 out and the last 2.10.6 now older than a year I'm not sure whether it makes sense for us to invest into swave for 2.10.
How long to you plan on supporting 2.10?

**Comment by fommil** [comment]
Until sbt isn't using it anymore, and everybody upgrades sbt. Otherwise we don't offer any ensime support for build files.

**Comment by fommil** [comment]
how much effort would it be for 2.10 do you think?

**Comment by sirthias** [comment]
Yeah, I figured that you hang off SBT. Do you know when is SBT planning on moving to 2.11?
For 2.10 support I think we need to follow shapeless' path of adding the typelevel macro-compat. Maybe that's already enough. Don't know...

**Comment by fommil** [comment]
hopefully they move to 2.12 with sbt 1.0! @dwijnand will know
