### ISSUE TITLE
A release without  ??? in the code?

### ISSUE THREAD

**Issue by joost-de-vries** [sirthias/swave#25]
I was wondering whether it's possible to provide a release without the ??? operator in it's implementation. 
I understand that using ??? is great while fleshing out an api. 
My concern is that at some point we'll have more complicated stream processing logic and that there may be the possibility of the system failing at runtime because of a corner case that hits an unimplemented operator.
To put it differently: I'm don't know how we can be absolutely sure that our code doesn't unwittingly depend on an unimplemented operator...

**Comment by sirthias** [comment]
Yes, that's a valid request.
One option could be to leave these methods in but mark them with `@compileTimeOnly` for the time being. That should do the trick of keeping the stubs visible but at the same time preventing accidental use in real code.

**Comment by joost-de-vries** [comment]
I didn't know that annotation. Yeah that sounds like the best of both worlds.

**Comment by joost-de-vries** [comment]
Wow. You're fast!
:-)
