### ISSUE TITLE
Missing "io.swave" %% "core-macros" % "0.5-M1" dependency

### ISSUE THREAD

**Issue by dnvriend** [sirthias/swave#4]
The core-macros is a dependency for swave-core, and sbt cannot resolve it. After searching for it on maven central it seems not to be published.

**Comment by dnvriend** [comment]
I had to fork the project, add `core-macros` to the aggregate project and comment  out `.settings(noPublishingSettings: _*)` from the `core-macros` project and do a `publishLocal` to get it to resolve.

**Comment by hicolour** [comment]
:+1: 

`[warn] 	:: io.swave#core-macros_2.11;0.5-M1: not found
`

**Comment by mushtaq** [comment]
Eager to try this out once dependency resolution works.

**Comment by sirthias** [comment]
Yes, this shows once more that releasing from a conference venue is generally not a good idea. Too many distractions... :-/
The `core-macros` sub-project is only a compile-time dependency and therefore shouldn't show up at all in the release artifact's POM. Clearly I've messed up the dependency configuration.

I'll fix this ASAP and published 0.5-M2.

Thank you, @dnvriend, for reporting!

**Comment by sirthias** [comment]
Ok, just pushed 0.5-M2 to sonatype.
Thanks again for reporting this problem!
