### ISSUE TITLE
Problem: test coverage not easily manageable

### ISSUE THREAD

**Issue by sirthias** [sirthias/swave#7]
Comprehensive test coverage is essential for being able to rely on automatic tests for

- reaching and maintaining high code quality
- making it easy to contribute and verify patches
- making it easy to refactor

Solution: Track code coverage automatically with [sbt-scoverage](https://github.com/scoverage/sbt-scoverage). Include README badge (see, for example, the shapeless README for inspiration).

**Comment by gvolpe** [comment]
Hi @sirthias, I've been trying to get this issue and [this one](https://github.com/sirthias/swave/issues/5) working, you can check out my fork [here](https://github.com/gvolpe/swave).

I've found a lot of problems with the time based tests like [AsyncSpec](https://github.com/sirthias/swave/blob/master/core-tests/src/test/scala/swave/core/AsyncSpec.scala) and [DropWithinSpec](https://github.com/sirthias/swave/blob/master/core-tests/src/test/scala/swave/core/impl/stages/DropWithinSpec.scala) among others. 

The Travis environment is different from our local environments, however even in my local environment I've got random failures of a few tests. Just for the record, the same Travis build has failed with 4, 3 and finally 6 tests after been triggered three times.

That said, I have to mention that I've also read the "Collective Code Construction Contract" in order to become a contributor. I will have some time to spare in the next six months so I would be glad to contribute in such challenging project.

Cheers,
Gabriel.

**Comment by sirthias** [comment]
Hey Gabriel, welcome aboard!

> I've found a lot of problems with the time based tests like AsyncSpec and DropWithinSpec among others. 

Yes, the time-sensitive tests can be a pain. They are two basic ways to deal with issues:

1. Redesign the (test-)architecture to allow for testing asynchronous behavior without having to specify environment-specific timeout values.
2. Tune/scale the timeout values to fit the test environment.

Option 1 would be better but is also much harder.
So option 2 might be the easier choice at this point.

The swave testkit already supports scaling timeout values via a config parameter (`swave.test.timing.factor`). By default it's set to `1.0` but you can override it with a command line setting that sets an environment variable with the same name. More detail on this can be found in the typesafe-config docs.

My suggestion for the initial travis setup would be to run with a travis-specific timing factor that is set via the travis command that starts the tests.

**Comment by gvolpe** [comment]
Thanks @sirthias !

Yes, I agree with you. For the initial Travis setup the second option is the easiest one. I will play around with this config parameter to see if I can get it working. I'll keep you posted!

**Comment by sirthias** [comment]
Great! Thanks again for your support!

**Comment by gvolpe** [comment]
Hi @sirthias ,

I tried changing the timing factor [quite a lot](https://github.com/gvolpe/swave/commits/master) without success until I decided to ignore AsyncSpec and one more test in ThrottleSpec, nevertheless the factor that seems to work the best was 1.05 (I left this configuration in the .travis.yml file). The first build is passing but is pure coincidence, still getting random failures, so I think that going back to the option one would be the best.

On the other hand, Coverall is working as expected, check out the [badges](https://github.com/gvolpe/swave).

Now you'll need to enable the original swave repository in Travis and Coveralls. Once you create them, I can point the badges to the proper servers.

Cheers,
Gabriel.

**Comment by sirthias** [comment]
Ok, if there is no way to stabilize the tests via the timing factor then we need to indeed touch the test code itself. So far I've been somewhat aggressive on timings in async tests since I don't want to slow down test running on our dev machines too much.
I'm pretty sure that there is a way to tweak the timeouts in the instable tests to make them pass nicely on travis.

How about you put in a PR with everything you have so far and simply disable all the instable tests? Then we can add a ticket addressing the problem of not having all the tests enabled in travis.

> On the other hand, Coverall is working as expected, check out the badges.

Sweet, that's great!

> Now you'll need to enable the original swave repository in Travis and Coveralls. Once you create them, I can point the badges to the proper servers.

Ok, I'll do that right away.

**Comment by sirthias** [comment]
Ok, travis and coveralls are now enabled for this repo.

**Comment by gvolpe** [comment]
Perfect! I'll do it this evening because I'm still working until the end of August, then I'll be kind of free.

**Comment by sirthias** [comment]
Muchas gracias and cheers to Buenos Aires!

**Comment by sirthias** [comment]
(or rather Dublin! :)

**Comment by gvolpe** [comment]
Gracias! Yeah, I'm in Dublin at the moment :)

**Comment by sirthias** [comment]
Closed by https://github.com/sirthias/swave/pull/11/commits/814429931dd1790bde5d0ebbd68e49ffb59eedbf.
