### ISSUE TITLE
Can you Retain ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [sirthias/swave#9]
ASL 2.0 is more widely used and more generally whitelisted in organisations. Is it possible to retain it? If you want to use C4 then fork it to accommodate ASL 2.0 either as dual license or just ASL 2.0.

**Comment by sirthias** [comment]
The decision on MPL 2.0 was made consciously after many discussions and a lot of thinking.
So, no, I'm sorry, swave will not be licensed under Apache 2.
What restrictions imposed by the MPL 2.0 are you concerned about in particular?

**Comment by adamwy** [comment]
I've noticed that LICENSE file contains the ASL 2.0 license. Are there parts of swave that are based on ASL 2.0?

**Comment by sirthias** [comment]
@adamwy Thanks for the heads-up regarding the LICENSE file. Its contents were a left-over from the initial setup of the repository. I've just changed it to the proper ASCII version of the MPL 2.0 license text, so it now matches all the file headers.
Thanks again!

**Comment by sirthias** [comment]
And (to answer your question): No, there are nothing in swave that's licensed under ASL 2.0.

**Comment by sirinath** [comment]
My concern is not with what restriction of the license but the effect on getting new contracts for work
1. % organization having MPL whitelisted vs BSD, MIT or ASL 2.0 and 
2. in case the client owns code and can relicense it as per contract you have to negotiate any use of copyleft license which cost money and takes time and if you follow through with this and do not get a deal all this is dead weight

Copyleft licences works well in products, companies using internally and utilities but is an additional burden if you develop bespoke software at a very small scale.

**Comment by sirthias** [comment]
Thanks for your perspective, @sirinath!

**Comment by sirinath** [comment]
No worries. So will you be reevaluating ASL 2.0 possibility? 

Also alternatives and more established projects like: Akka Streams, http://reactors.io/, RxJava, http://projectreactor.io/, http://vertx.io/, https://monix.io/ have more permisive licenses. It will be great, in my perspective, if you follow the same.
